# Generated by Django 5.1 on 2024-08-31 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='details',
            new_name='Details',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='name',
            new_name='Name',
        ),
    ]
